// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Order : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Order"",""namespace"":""avro"",""fields"":[{""name"":""orderID"",""type"":""int""},{""name"":""totalCost"",""type"":""double""},{""name"":""createdAt"",""type"":""long""},{""name"":""dishesList"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Dishes"",""namespace"":""avro"",""fields"":[{""name"":""dishId"",""type"":""int""},{""name"":""title"",""type"":""string""}]}}}]}");
		private int _orderID;
		private double _totalCost;
		private long _createdAt;
		private IList<avro.Dishes> _dishesList;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Order._SCHEMA;
			}
		}
		public int orderID
		{
			get
			{
				return this._orderID;
			}
			set
			{
				this._orderID = value;
			}
		}
		public double totalCost
		{
			get
			{
				return this._totalCost;
			}
			set
			{
				this._totalCost = value;
			}
		}
		public long createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				this._createdAt = value;
			}
		}
		public IList<avro.Dishes> dishesList
		{
			get
			{
				return this._dishesList;
			}
			set
			{
				this._dishesList = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.orderID;
			case 1: return this.totalCost;
			case 2: return this.createdAt;
			case 3: return this.dishesList;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.orderID = (System.Int32)fieldValue; break;
			case 1: this.totalCost = (System.Double)fieldValue; break;
			case 2: this.createdAt = (System.Int64)fieldValue; break;
			case 3: this.dishesList = (IList<avro.Dishes>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
